In [18]:
import pandas as pd
import numpy as np

df = pd.read_excel("notes_option_info.xlsx").iloc[:45]
df["id"] = df["id"].astype(int)
df = df.set_index("id")[["ds1"]]
df

            ds1
id
188   17.050637
77    11.357696
1411   7.612341
248    7.312712
412    9.410111
41     7.762155
296   18.698593
1411   9.110483
48     5.065499
44     9.859554
315    4.316428
3012   7.762155
318   17.649894
2912   5.215313
15     8.810855
2012   7.612341
1512   8.511226
910   14.653609
305    9.559926
206   10.009368
39     3.417543
119   12.406396
241    7.762155
18     9.709740
167    7.762155
142   10.009368
2011   7.013084
1611   6.563641
91    13.904538
33    16.151752
281   12.406396
307    9.559926
153    7.162898
201   10.608625
273    5.964384
105    9.559926
235    8.810855
42    11.058068
611   11.507511
265    7.312712
225    8.361412
239    3.417543
178   11.657325
312   11.807139
1410   6.264013

In [19]:
for col in df.select_dtypes(include=['object']).columns:
    df[col] = df[col].str.replace(',', '.').astype('float')
# df.index = df.index.astype(int)
df.to_csv("grade.csv")